name: Branch is up to date

on:
  pull_request:

jobs:
  check-branch-up-to-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Fetch Default Branch
        run: git fetch origin ${{ github.event.repository.default_branch }}

      - name: Compare with Default Branch
        id: compare
        run: |
          DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
          DEFAULT_HASH=$(git rev-parse origin/$DEFAULT_BRANCH)
          PR_BRANCH_HASH=$(git merge-base HEAD origin/$DEFAULT_BRANCH)
      
          if [ "$DEFAULT_HASH" = "$PR_BRANCH_HASH" ] || [ "$(git rev-list --count $DEFAULT_HASH..HEAD)" -gt 0 ]; then
            echo "Branch is up-to-date with or ahead of the default branch ($DEFAULT_BRANCH)."
          else
            echo "Branch is not up-to-date with the default branch ($DEFAULT_BRANCH)."
            exit 1
          fi

      - name: Notify Success
        if: success()
        run: echo "The PR branch is up-to-date with the default branch."
